"""Configuration for hazard label generation workflows."""

from __future__ import annotations

import os
from dataclasses import dataclass, field


def _env_flag(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    return float(raw)


def _env_csv_set(name: str, default: tuple[str, ...]) -> tuple[str, ...]:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    values = [item.strip().lower() for item in raw.split(",") if item.strip()]
    return tuple(values) or default


@dataclass(frozen=True)
class FlashFloodLabelMappingConfig:
    point_buffer_km: float = 25.0
    province_fallback_enabled: bool = True
    emit_event_day_negatives: bool = True
    min_spatial_confidence: str = "medium"
    positive_validation_statuses: tuple[str, ...] = ("seed", "verified")
    location_to_province: dict[str, str] = field(
        default_factory=lambda: {
            "jeddah": "makkah",
            "jedda": "makkah",
            "mecca": "makkah",
            "makkah": "makkah",
            "makkah province": "makkah",
            "makkah region": "makkah",
            "makkah high altitude regions": "makkah",
            "makkah high-altitude regions": "makkah",
            "taif": "makkah",
            "maysan": "makkah",
            "rabigh": "makkah",
            "riyadh": "riyadh",
            "riyadh region": "riyadh",
            "eastern": "eastern province",
            "eastern province": "eastern province",
            "eastern region": "eastern province",
            "dammam": "eastern province",
            "medina": "madinah",
            "madinah": "madinah",
            "madinah province": "madinah",
            "al madinah region": "madinah",
            "yanbu": "madinah",
            "al hanakiyah": "madinah",
            "al ula": "madinah",
            "al-ula": "madinah",
            "al ula region": "madinah",
            "al-ula region": "madinah",
            "fadhlan valley": "madinah",
            "khaybar": "madinah",
            "hail": "hail",
            "hail region": "hail",
            "ha'il": "hail",
            "ha'il region": "hail",
            "hayel region": "hail",
            "qassim": "qassim",
            "qaseem": "qassim",
            "qassim region": "qassim",
            "al-qassim region": "qassim",
            "jazan": "jazan",
            "jizan": "jazan",
            "jazan region": "jazan",
            "tabuk": "tabuk",
            "tabuk region": "tabuk",
            "duba": "tabuk",
            "wajh": "tabuk",
            "umluj": "tabuk",
            "hafar al-batin": "eastern province",
            "hafar al batin": "eastern province",
            "najran": "najran",
            "najran region": "najran",
            "sharurah": "najran",
            "asir": "asir",
            "aseer": "asir",
            "'asir region": "asir",
            "abha": "asir",
            "khamis mushait": "asir",
            "al bahah": "al bahah",
            "al baha": "al bahah",
            "al-baha": "al bahah",
            "baha": "al bahah",
            "al bahah region": "al bahah",
            "al jawf": "al jawf",
            "jawf": "al jawf",
            "al jawf region": "al jawf",
            "northern borders": "northern borders",
            "northern border province": "northern borders",
            "northern borders region": "northern borders",
            "arar": "northern borders",
            "rumah": "riyadh",
            "huraymila": "riyadh",
            "turaif": "northern borders",
            "alula": "madinah",
        }
    )

    @classmethod
    def from_env(cls) -> "FlashFloodLabelMappingConfig":
        return cls(
            point_buffer_km=_env_float("MAZU_FLASH_FLOOD_POINT_BUFFER_KM", 25.0),
            province_fallback_enabled=_env_flag("MAZU_FLASH_FLOOD_PROVINCE_FALLBACK_ENABLED", True),
            emit_event_day_negatives=_env_flag("MAZU_FLASH_FLOOD_EMIT_EVENT_DAY_NEGATIVES", True),
            min_spatial_confidence=os.getenv("MAZU_FLASH_FLOOD_MIN_SPATIAL_CONFIDENCE", "medium").strip().lower() or "medium",
            positive_validation_statuses=_env_csv_set("MAZU_FLASH_FLOOD_POSITIVE_VALIDATION_STATUSES", ("seed", "verified")),
        )


@dataclass(frozen=True)
class ExtremeHeatLabelMappingConfig:
    location_to_region_ids: dict[str, tuple[str, ...]] = field(
        default_factory=lambda: {
            "arafat": ("makkah",),
            "arafat near makkah": ("makkah",),
            "al ahsa": ("eastern_province",),
            "al ahsa al kharj": ("eastern_province", "riyadh"),
            "al hassa": ("eastern_province",),
            "al kharj": ("riyadh",),
            "al majmaah": ("riyadh",),
            "al qaisumah": ("eastern_province",),
            "dhahran": ("eastern_province",),
            "eastern arabia interior": ("eastern_province",),
            "eastern province and madinah yanbu areas": ("eastern_province", "madinah"),
            "eastern province and riyadh": ("eastern_province", "riyadh"),
            "eastern province coastal areas": ("eastern_province",),
            "interior eastern arabia": ("eastern_province",),
            "jeddah and other areas": ("makkah",),
            "makkah and hajj sites": ("makkah",),
            "makkah and madinah regions": ("makkah", "madinah"),
            "mecca and hajj sites": ("makkah",),
            "mecca and medina": ("makkah", "madinah"),
            "mount arafat": ("makkah",),
            "multiple cities": ("saudi_arabia",),
            "nationwide": ("saudi_arabia",),
            "rafha": ("northern_borders",),
            "saudi arabia": ("saudi_arabia",),
            "saudi arabia nationwide": ("saudi_arabia",),
            "sharurah": ("najran",),
        }
    )

    @classmethod
    def from_env(cls) -> "ExtremeHeatLabelMappingConfig":
        return cls()


@dataclass(frozen=True)
class DustStormLabelMappingConfig:
    emit_event_day_negatives: bool = True
    positive_validation_statuses: tuple[str, ...] = ("verified",)
    location_aliases: dict[str, str] = field(
        default_factory=lambda: {
            "asir": "asir",
            "asir region": "asir",
            "'asir region": "asir",
            "aseer": "asir",
            "dammam": "eastern_province",
            "eastern": "eastern_province",
            "eastern province": "eastern_province",
            "eastern_region": "eastern_province",
            "easternprovince": "eastern_province",
            "eastern region": "eastern_province",
            "hafar al-batin": "eastern_province",
            "hail": "hail",
            "hafar al batin": "eastern_province",
            "hail region": "hail",
            "hejaz": "hijaz",
            "hijaz": "hijaz",
            "jizan": "jizan",
            "jazan": "jazan",
            "jazan region": "jazan",
            "jizan region": "jazan",
            "madinah": "madinah",
            "medina": "madinah",
            "al madinah region": "madinah",
            "madinah region": "madinah",
            "medina region": "madinah",
            "najran": "najran",
            "najran region": "najran",
            "northern borders": "northern_borders",
            "northern_borders": "northern_borders",
            "northern borders region": "northern_borders",
            "qassim": "qassim",
            "qaseem": "qassim",
            "al qassim region": "qassim",
            "qassim region": "qassim",
            "rafha": "northern_borders",
            "riyadh": "riyadh",
            "riyadh region": "riyadh",
            "al bahah region": "al_bahah",
            "al jawf region": "al_jawf",
            "makkah region": "makkah",
            "tabuk region": "tabuk",
        }
    )
    location_to_region_ids: dict[str, tuple[str, ...]] = field(
        default_factory=lambda: {
            "riyadh": ("riyadh",),
            "bisha": ("asir",),
            "qurayyat": ("al_jawf",),
            "khamis mushait": ("asir",),
            "turaif": ("northern_borders",),
            "sharurah": ("najran",),
            "unaizah": ("qassim",),
            "wadi ad-dawasir": ("riyadh",),
            "al-kharj": ("riyadh",),
            "dhahran": ("eastern_province",),
            "buraydah": ("qassim",),
            "al-majmaah": ("riyadh",),
            "dawadmi": ("riyadh",),
            "al-ula": ("madinah",),
            "qatif": ("eastern_province",),
            "al lith": ("makkah",),
            "rabigh": ("makkah",),
            "al quwaiiyah": ("riyadh",),
            "duba": ("tabuk",),
            "al wajh": ("tabuk",),
            "tayma": ("tabuk",),
            "al zulfi": ("riyadh",),
            "al mithnab": ("qassim",),
            "badr": ("madinah",),
            "al namas": ("asir",),
            "al aflaj": ("riyadh",),
            "al rass": ("qassim",),
            "al qunfudhah": ("makkah",),
            "shaqra": ("riyadh",),
            "al hinakiyah": ("madinah",),
            "mahd adh dhahab": ("madinah",),
            "al mubarraz": ("eastern_province",),
            "al jafr": ("eastern_province",),
            "al darb": ("jazan",),
            "al haditha": ("northern_borders",),
            "al nabhaniyah": ("qassim",),
            "al shumaisi": ("makkah",),
            "afif": ("riyadh",),
            "khaybar": ("madinah",),
            "al duwadimi": ("riyadh",),
            "dumat al-jandal": ("al_jawf",),
            "al sulayyil": ("riyadh",),
            "haql": ("tabuk",),
            "umluj": ("tabuk",),
            "baljurashi": ("al_bahah",),
            "sabya": ("jazan",),
            "thadiq": ("riyadh",),
            "al-bukayriyah": ("qassim",),
            "al-asyah": ("qassim",),
            "sarat abidah": ("asir",),
            "ranyah": ("makkah",),
            "farasan island": ("jazan",),
            "hawtat sudayr": ("riyadh",),
            "durma": ("riyadh",),
            "thuwal": ("makkah",),
            "al-mandaq": ("al_bahah",),
            "al-hariq": ("riyadh",),
            "al-makhwah": ("al_bahah",),
            "al-khurmah": ("makkah",),
            "al-bada'i": ("qassim",),
            "al-hamra (madinah)": ("madinah",),
            "jeddah": ("makkah",),
            "al bahah": ("al_bahah",),
            "tabuk": ("tabuk",),
            "rafha": ("northern_borders",),
            "abha": ("asir",),
            "yanbu": ("madinah",),
            "hail": ("hail",),
            "jubail": ("eastern_province",),
            "najran": ("najran",),
            "taif": ("makkah",),
            "sakaka": ("al_jawf",),
            "arar": ("northern_borders",),
            "medina": ("madinah",),
            "mecca": ("makkah",),
            "dammam": ("eastern_province",),
            "hofuf": ("eastern_province",),
            "hafar al-batin": ("eastern_province",),
            "jazan": ("jazan",),
            "khobar": ("eastern_province",),
            "al qaisumah": ("eastern_province",),
            "al khafji": ("eastern_province",),
            "al nairiyah": ("eastern_province",),
            "al ghat": ("riyadh",),
            "rumah": ("riyadh",),
            "layla": ("riyadh",),
            "ad dilam": ("riyadh",),
            "al artawiyah": ("riyadh",),
            "almuzahimiyah": ("riyadh",),
            "ras tanura": ("eastern_province",),
            "al-kamil": ("makkah",),
            "al-eis": ("madinah",),
            "tanomah": ("asir",),
            "al-aqiq": ("al_bahah",),
            "al-jalamid": ("northern_borders",),
            "tabarjal": ("al_jawf",),
            "al-bad'": ("tabuk",),
            "al-shamli": ("hail",),
            "abu arish": ("jazan",),
            "habuna": ("najran",),
            "almuwayh": ("makkah",),
            "wadi al-fara'": ("madinah",),
            "abqaiq": ("eastern_province",),
            "samtah": ("jazan",),
            "al jishah": ("eastern_province",),
            "rijal alma": ("asir",),
            "safwa": ("eastern_province",),
            "qilwah": ("al_bahah",),
            "saihat": ("eastern_province",),
            "al-oyoon": ("eastern_province",),
            "tarut": ("eastern_province",),
            "khulais": ("makkah",),
            "huraymila": ("riyadh",),
            "tathlith": ("asir",),
            "sabt al alaya": ("asir",),
            "al-majardah": ("asir",),
            "tumair": ("riyadh",),
            "jalajil": ("riyadh",),
            "dhahran al-janub": ("asir",),
            "turabah": ("makkah",),
            "al jumum": ("makkah",),
            "al uqair": ("eastern_province",),
            "al qarah": ("eastern_province",),
            "diriyah": ("riyadh",),
            "baysh": ("jazan",),
            "muhayil": ("asir",),
            "al qura": ("makkah",),
            "al hada": ("makkah",),
            "al shafa": ("makkah",),
            "al tuwal": ("jazan",),
            "al-khuraybah": ("tabuk",),
            "uyun al-jiwa": ("qassim",),
            "al-ruwaidhah": ("riyadh",),
            "bareq": ("asir",),
            "al-ha'it": ("hail",),
            "al-malihah": ("madinah",),
            "ahad rafidah": ("asir",),
            "yadamah": ("najran",),
            "al-awamiyah": ("eastern_province",),
            "al-uwayqilah": ("northern_borders",),
            "qaryat al-ulya": ("eastern_province",),
            "al-soudah": ("asir",),
            "al-ghazalah": ("hail",),
            "al-muwassam": ("jazan",),
            "al-atawilah": ("al_bahah",),
            "al-muzaylif": ("makkah",),
            "al-hafirah": ("riyadh",),
            "al-munizlah": ("eastern_province",),
            "al-shuqaiq": ("jazan",),
            "al-harjah": ("asir",),
            "al-mutairifi": ("eastern_province",),
            "al-khobah": ("jazan",),
            "al-udailiyah": ("eastern_province",),
            "al-jafr (eastern province)": ("eastern_province",),
            "ar-ruwaidhah (qassim)": ("qassim",),
            "al-madhyah": ("al_bahah",),
            "al-mundassah": ("hail",),
            "ash-shinan": ("qassim",),
            "al-husayni": ("asir",),
            "al-yamamah": ("riyadh",),
            "al-uyaynah": ("riyadh",),
            "al-faw": ("riyadh",),
            "al-ashqar": ("riyadh",),
            "al-thumamah": ("riyadh",),
            "al-mazari": ("riyadh",),
            "al-qurayya": ("tabuk",),
            "ash-shamasiyah": ("qassim",),
            "al-sarrar": ("eastern_province",),
            "al-ammariyah": ("riyadh",),
            "al-khubra": ("qassim",),
            "al-kharkhair": ("najran",),
            "al-hanakiya": ("madinah",),
            "al-mulaylih": ("riyadh",),
            "al-wuday": ("asir",),
            "al-hashm": ("qassim",),
            "al-marwah": ("najran",),
            "al-hujayrah": ("al_bahah",),
            "al-qurayyat": ("al_jawf",),
            "al-bahah (city)": ("al_bahah",),
            "al-hada (eastern province)": ("eastern_province",),
            "al-hijr": ("madinah",),
            "al-juhfah": ("makkah",),
            "al-mahjar": ("makkah",),
            "al-qaa": ("tabuk",),
            "al-dayer bani malik": ("jazan",),
            "al-farsha": ("asir",),
            "al-aridah": ("jazan",),
            "al-taraf": ("eastern_province",),
            "al-hazm": ("al_jawf",),
            "saudi_arabia": ("saudi_arabia",),
        }
    )

    @classmethod
    def from_env(cls) -> "DustStormLabelMappingConfig":
        return cls(
            emit_event_day_negatives=_env_flag("MAZU_DUST_STORM_EMIT_EVENT_DAY_NEGATIVES", True),
            positive_validation_statuses=_env_csv_set("MAZU_DUST_STORM_POSITIVE_VALIDATION_STATUSES", ("verified",)),
        )
